### ISSUE TITLE
v9.22

### ISSUE THREAD

**Issue by matthewheil** [AlioptK/DiscoLoL#1]
Hi, 

I'm running v9.22 and it doesn't seem like DiscoLoL is working. I downloaded the most recent version of DiscoLoL (11/14/2019) and verified that my region, NA, and the chat server are correct in the config.yaml file.

**Comment by EmileDqy** [comment]
Hello, I've configured my friend's config file the other day and it worked perfectly fine. It's quite strange.
The chat servers changed tho in his. 

Did you find the root of the problem since then? If not then I'll try to see what went wrong by the end of the week. 

Sorry for the wait.

**Comment by matthewheil** [comment]
I have Norton antivirus that manages the Windows firewall, which I suspect is the issue. If I find a solution, I'll update here. Thanks

**Comment by matthewheil** [comment]
The issue was with the Windows firewall being managed. I tested uninstalling Norton and the program (firewall rule) worked.
